/**
 * Generated by tsnapi — public API snapshot of `last-lines` */
// Interfaces
export interface LastLinesOptions {
  chunkSize?: number;
  encoding?: BufferEncoding;
}

// Functions
export declare function lastLines(_: PathLike, _: number, _?: LastLinesOptions): Promise<string[]>;
export declare function lastLinesSync(_: PathLike, _: number, _?: LastLinesOptions): string[];

// Variables
export declare const readLastLines: typeof lastLines;
export declare const readLastLinesSync: typeof lastLinesSync;